spring.application.name=chapter13-3

server.port=8081
# ??AI API ?? ?
spring.ai.openai.api-key=${OPENAI_API_KEY}

# ?? STT ?? ??
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json

# Speech(TTS) ?? ??(default)
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.voice=alloy
spring.ai.openai.audio.speech.options.response-format=mp3
spring.ai.openai.audio.speech.options.speed=1.0