spring.application.name=chapter12-1

server.port=8081
spring.ai.openai.api-key=${OPENAI_API_KEY}

# ???? ??? ??? ?? ??
spring.servlet.multipart.max-file-size=10MB

# ??? ?? ?? ??
spring.ai.openai.image.options.model=dall-e-3
spring.ai.openai.image.options.quality=hd
spring.ai.openai.image.options.size=1024x1024