spring.application.name=chapter03-4

server.port=8081

# OpenAI ?? (??)
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.8
# spring.ai.openai.chat.options.max_tokens=2000
