spring.application.name=chapter06-1

server.port=8081
# OpenAI API ? (?? ?? ?? ??)
spring.ai.openai.api-key=${OPENAI_API_KEY}
# ??? ?? ??
spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.chat.options.temperature=1.0
# ??? ?????? ?? ??? ??? ???? ?? ??
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/chatmemory
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
