spring.application.name=chapter13-1

server.port=8081
# ??AI API ?? ?
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.chat.options.temperature=1.0

# ?? STT ?? ??
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json