spring.application.name=chapter11-1-client

server.port=8081
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5-mini
spring.ai.openai.chat.options.temperature=1.0
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# 1. stdio ???? ??? ??
# spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
# -------------------------------------------------1 END-----------

# 2.  streamable-http ?? MCP ?? ?? URL ??? ??
spring.ai.mcp.client.name=mcp-client
spring.ai.mcp.client.version=0.0.1
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.streamable-http.connections.mymcp.url=http://localhost:8181/mcp
# -------------------------------------------------2 END----------------
